### ISSUE TITLE
Download never finish, randomly stuck.

### ISSUE THREAD

**Issue by gitNemo** [tmacharia/download-client#5]
`        private void Button_Click(object sender, RoutedEventArgs e)
        {
            IDownloader _downloader = new Neon.Downloader.DownloaderClient();
            _downloader.OnDownloading += _downloader_OnDownloading;
            _downloader.DownloadCompleted += _downloader_DownloadCompleted;
            _downloader.OnError += _downloader_OnError;
            _downloader.DownloadToFile("ANY URL", "a");
        }

        private void _downloader_OnError(Exception ex)
        {
            Debug.WriteLine($"ERROR: {ex.Message}");
        }

        private void _downloader_DownloadCompleted(DownloadMetric metric, System.IO.Stream stream)
        {
            Debug.WriteLine("DOWNLOAD COMPLETE");
        }

        private void _downloader_OnDownloading(DownloadMetric metric)
        {
            Dispatcher.Invoke(() =>
            {
                tt.Text = metric.Progress.ToString();
            });
            
        }`

**Comment by tmacharia** [comment]
Thanks for raising this. I figured it was a small issue with figuring out the number of bytes to download from the total number of bytes. The issue has been fixed in this pull request #6 

Please update to the [newest version v1.0.4](https://www.nuget.org/packages/Download.Client/1.0.4)
